### ISSUE TITLE
System.ArgumentOutOfRangeException error

### ISSUE THREAD

**Issue by ganesh-nadar-db** [google-github-actions/auth#347]
### TL;DR

Hi Team,
Getting below error when calling action google-github-actions/auth@v1
```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node1[6](https://github.com/v4qn-a4j2/ars-temp/actions/runs/6934740349/job/18863475567#step:4:6)' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load google-github-actions/auth/v1/action.yml
```

This was working fine until few moments before and started to fail suddenly

### Expected behavior

Auth action should run successfully

### Observed behavior

Auth action fails

### Action YAML

```yaml
name: Common steps
description: Configure common steps
inputs:
 ...
 ...


runs:
  using: "composite"
  
  steps:
    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        workload_identity_provider: ${{ inputs.DEFAULT_WIF_PROVIDER }}
        service_account: ${{ inputs.PIPELINE_SERVICE_ACCOUNT }}

......
......
```

### Log output

```text
Prepare all required actions
Getting action download info
Download action repository 'google-github-actions/auth@v1' (SHA:f105ef0cdb3b102a020be1767fcc8a974898b7c6)
Download action repository 'google-github-actions/get-secretmanager-secrets@v1' (SHA:4d6d3dfd94110800dda8d84109cb6da0f6a5919d)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load google-github-actions/auth/v1/action.yml
```

**Comment by sethvargo** [comment]
Hi @ganesh-nadar-db, Node 16 was EOL on 2023-09-11 and no longer receives security updates or patches. The GitHub-managed runners have moved to Node 20 and no longer support Node 16. 

If you're using self-hosted runners, you can pin to v1.1.1.

**Comment by cread** [comment]
But this is a major change, why not release this as `v2`?

**Comment by sethvargo** [comment]
Hi @cread thank you for the feedback. We'll release the other actions as a major release.

**Comment by jordi-gomez-db** [comment]
> But this is a major change, why not release this as `v2`?

Completely agree with you, this is causing a major problem in our project, almost every workflow is failing.
